# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CourseEntryDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CourseEntryDlg(object):
    def setupUi(self, CourseEntryDlg):
        CourseEntryDlg.setObjectName(_fromUtf8("CourseEntryDlg"))
        CourseEntryDlg.resize(516, 378)
        self.buttonBox = QtGui.QDialogButtonBox(CourseEntryDlg)
        self.buttonBox.setGeometry(QtCore.QRect(160, 340, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(CourseEntryDlg)
        self.groupBox.setGeometry(QtCore.QRect(190, 10, 318, 311))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.addBtn = QtGui.QPushButton(self.groupBox)
        self.addBtn.setGeometry(QtCore.QRect(220, 270, 85, 27))
        self.addBtn.setObjectName(_fromUtf8("addBtn"))
        self.MPTable = QtGui.QTableWidget(self.groupBox)
        self.MPTable.setGeometry(QtCore.QRect(10, 130, 291, 131))
        self.MPTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.MPTable.setAlternatingRowColors(True)
        self.MPTable.setShowGrid(False)
        self.MPTable.setRowCount(0)
        self.MPTable.setColumnCount(3)
        self.MPTable.setObjectName(_fromUtf8("MPTable"))
        self.splitter_5 = QtGui.QSplitter(self.groupBox)
        self.splitter_5.setGeometry(QtCore.QRect(10, 30, 291, 81))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_6 = QtGui.QLabel(self.splitter_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.locEdit = QtGui.QLineEdit(self.splitter_2)
        self.locEdit.setObjectName(_fromUtf8("locEdit"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_7 = QtGui.QLabel(self.splitter_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.dayCombo = QtGui.QComboBox(self.splitter_3)
        self.dayCombo.setObjectName(_fromUtf8("dayCombo"))
        self.dayCombo.addItem(_fromUtf8(""))
        self.dayCombo.addItem(_fromUtf8(""))
        self.dayCombo.addItem(_fromUtf8(""))
        self.dayCombo.addItem(_fromUtf8(""))
        self.dayCombo.addItem(_fromUtf8(""))
        self.splitter_4 = QtGui.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label_8 = QtGui.QLabel(self.splitter_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.splitter = QtGui.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tStartEdit = QtGui.QTimeEdit(self.splitter)
        self.tStartEdit.setObjectName(_fromUtf8("tStartEdit"))
        self.label_10 = QtGui.QLabel(self.splitter)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tEndEdit = QtGui.QTimeEdit(self.splitter)
        self.tEndEdit.setObjectName(_fromUtf8("tEndEdit"))
        self.groupBox_2 = QtGui.QGroupBox(CourseEntryDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 181, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 101, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.splitter_7 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_7.setGeometry(QtCore.QRect(0, 240, 172, 22))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.label_5 = QtGui.QLabel(self.splitter_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.creditEdit = QtGui.QLineEdit(self.splitter_7)
        self.creditEdit.setObjectName(_fromUtf8("creditEdit"))
        self.splitter_8 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_8.setGeometry(QtCore.QRect(0, 30, 172, 22))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.label = QtGui.QLabel(self.splitter_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.codeEdit = QtGui.QLineEdit(self.splitter_8)
        self.codeEdit.setObjectName(_fromUtf8("codeEdit"))
        self.splitter_9 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_9.setGeometry(QtCore.QRect(0, 58, 172, 22))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.label_2 = QtGui.QLabel(self.splitter_9)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.titleEdit = QtGui.QLineEdit(self.splitter_9)
        self.titleEdit.setObjectName(_fromUtf8("titleEdit"))
        self.splitter_10 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_10.setGeometry(QtCore.QRect(0, 120, 171, 111))
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.instList = QtGui.QListWidget(self.splitter_10)
        self.instList.setObjectName(_fromUtf8("instList"))
        self.splitter_6 = QtGui.QSplitter(self.splitter_10)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.instEdit = QtGui.QLineEdit(self.splitter_6)
        self.instEdit.setObjectName(_fromUtf8("instEdit"))
        self.instAddBtn = QtGui.QPushButton(self.splitter_6)
        self.instAddBtn.setObjectName(_fromUtf8("instAddBtn"))

        self.retranslateUi(CourseEntryDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CourseEntryDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CourseEntryDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(CourseEntryDlg)

    def retranslateUi(self, CourseEntryDlg):
        CourseEntryDlg.setWindowTitle(_translate("CourseEntryDlg", "CourseEntry", None))
        self.groupBox.setTitle(_translate("CourseEntryDlg", "Meeting Patterns", None))
        self.addBtn.setText(_translate("CourseEntryDlg", "Add", None))
        self.label_6.setText(_translate("CourseEntryDlg", "Location", None))
        self.label_7.setText(_translate("CourseEntryDlg", "Day", None))
        self.dayCombo.setItemText(0, _translate("CourseEntryDlg", "Monday", None))
        self.dayCombo.setItemText(1, _translate("CourseEntryDlg", "Tuesday", None))
        self.dayCombo.setItemText(2, _translate("CourseEntryDlg", "Wednesday", None))
        self.dayCombo.setItemText(3, _translate("CourseEntryDlg", "Thursday", None))
        self.dayCombo.setItemText(4, _translate("CourseEntryDlg", "Friday", None))
        self.label_8.setText(_translate("CourseEntryDlg", "Time", None))
        self.label_10.setText(_translate("CourseEntryDlg", "-", None))
        self.groupBox_2.setTitle(_translate("CourseEntryDlg", "Information", None))
        self.label_3.setText(_translate("CourseEntryDlg", "Instructors :", None))
        self.label_5.setText(_translate("CourseEntryDlg", "Credit", None))
        self.label.setText(_translate("CourseEntryDlg", "Code", None))
        self.label_2.setText(_translate("CourseEntryDlg", "Title", None))
        self.instAddBtn.setText(_translate("CourseEntryDlg", "Add", None))

