# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(606, 359)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.splitter_5 = QtGui.QSplitter(self.centralWidget)
        self.splitter_5.setGeometry(QtCore.QRect(20, 50, 261, 121))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.splitter = QtGui.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.code = QtGui.QLineEdit(self.splitter)
        self.code.setObjectName(_fromUtf8("code"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_2 = QtGui.QLabel(self.splitter_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.title = QtGui.QLineEdit(self.splitter_2)
        self.title.setObjectName(_fromUtf8("title"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_3 = QtGui.QLabel(self.splitter_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.instructors = QtGui.QComboBox(self.splitter_3)
        self.instructors.setObjectName(_fromUtf8("instructors"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label_4 = QtGui.QLabel(self.splitter_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.credit = QtGui.QLineEdit(self.splitter_4)
        self.credit.setToolTip(_fromUtf8(""))
        self.credit.setObjectName(_fromUtf8("credit"))
        self.splitter_10 = QtGui.QSplitter(self.centralWidget)
        self.splitter_10.setGeometry(QtCore.QRect(290, 50, 301, 241))
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.splitter_8 = QtGui.QSplitter(self.splitter_10)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.splitter_7 = QtGui.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.label_5 = QtGui.QLabel(self.splitter_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.myCourses = QtGui.QListWidget(self.splitter_7)
        self.myCourses.setObjectName(_fromUtf8("myCourses"))
        self.splitter_9 = QtGui.QSplitter(self.splitter_10)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.removeBtn = QtGui.QPushButton(self.splitter_9)
        self.removeBtn.setObjectName(_fromUtf8("removeBtn"))
        self.clearBtn = QtGui.QPushButton(self.splitter_9)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.colorBtn = QtGui.QPushButton(self.splitter_9)
        self.colorBtn.setObjectName(_fromUtf8("colorBtn"))
        self.openSchedule = QtGui.QPushButton(self.centralWidget)
        self.openSchedule.setGeometry(QtCore.QRect(20, 246, 121, 41))
        self.openSchedule.setObjectName(_fromUtf8("openSchedule"))
        self.splitter_6 = QtGui.QSplitter(self.centralWidget)
        self.splitter_6.setGeometry(QtCore.QRect(20, 0, 571, 41))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.pool = QtGui.QComboBox(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pool.sizePolicy().hasHeightForWidth())
        self.pool.setSizePolicy(sizePolicy)
        self.pool.setObjectName(_fromUtf8("pool"))
        self.selectBtn = QtGui.QPushButton(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setObjectName(_fromUtf8("selectBtn"))
        self.newBtn = QtGui.QPushButton(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newBtn.sizePolicy().hasHeightForWidth())
        self.newBtn.setSizePolicy(sizePolicy)
        self.newBtn.setObjectName(_fromUtf8("newBtn"))
        self.deleteBtn = QtGui.QPushButton(self.splitter_6)
        self.deleteBtn.setObjectName(_fromUtf8("deleteBtn"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 606, 25))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Save = QtGui.QMenu(self.menuFile)
        self.menu_Save.setObjectName(_fromUtf8("menu_Save"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuDisplay = QtGui.QMenu(self.menuBar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionCode = QtGui.QAction(MainWindow)
        self.actionCode.setCheckable(True)
        self.actionCode.setChecked(False)
        self.actionCode.setObjectName(_fromUtf8("actionCode"))
        self.actionTitle = QtGui.QAction(MainWindow)
        self.actionTitle.setCheckable(True)
        self.actionTitle.setChecked(True)
        self.actionTitle.setEnabled(True)
        self.actionTitle.setObjectName(_fromUtf8("actionTitle"))
        self.actionInstructor = QtGui.QAction(MainWindow)
        self.actionInstructor.setCheckable(True)
        self.actionInstructor.setChecked(False)
        self.actionInstructor.setEnabled(True)
        self.actionInstructor.setObjectName(_fromUtf8("actionInstructor"))
        self.actionSchedule = QtGui.QAction(MainWindow)
        self.actionSchedule.setObjectName(_fromUtf8("actionSchedule"))
        self.actionCourses = QtGui.QAction(MainWindow)
        self.actionCourses.setObjectName(_fromUtf8("actionCourses"))
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.menu_Save.addAction(self.actionCourses)
        self.menu_Save.addAction(self.actionSchedule)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.menu_Save.menuAction())
        self.menuDisplay.addAction(self.actionTitle)
        self.menuDisplay.addAction(self.actionCode)
        self.menuDisplay.addAction(self.actionInstructor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuDisplay.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "OlinScheduler", None))
        self.label.setText(_translate("MainWindow", "Code :", None))
        self.label_2.setText(_translate("MainWindow", "Title :", None))
        self.label_3.setText(_translate("MainWindow", "Instructors :", None))
        self.label_4.setText(_translate("MainWindow", "Credit :", None))
        self.label_5.setText(_translate("MainWindow", "My Courses : ", None))
        self.removeBtn.setToolTip(_translate("MainWindow", "Remove selected course from my list", None))
        self.removeBtn.setText(_translate("MainWindow", "Remove", None))
        self.clearBtn.setToolTip(_translate("MainWindow", "Clear all of my courses", None))
        self.clearBtn.setText(_translate("MainWindow", "Clear", None))
        self.colorBtn.setToolTip(_translate("MainWindow", "Apply color to my courses", None))
        self.colorBtn.setText(_translate("MainWindow", "Colorize", None))
        self.openSchedule.setToolTip(_translate("MainWindow", "Opens Schedule Window.", None))
        self.openSchedule.setText(_translate("MainWindow", "Schedule View", None))
        self.pool.setToolTip(_translate("MainWindow", "The List of All Available Courses", None))
        self.selectBtn.setToolTip(_translate("MainWindow", "Add selected course to my courses", None))
        self.selectBtn.setText(_translate("MainWindow", "Select", None))
        self.newBtn.setToolTip(_translate("MainWindow", "Create a new course entry", None))
        self.newBtn.setText(_translate("MainWindow", "New", None))
        self.deleteBtn.setToolTip(_translate("MainWindow", "Delete selected course entry", None))
        self.deleteBtn.setText(_translate("MainWindow", "Delete", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menu_Save.setTitle(_translate("MainWindow", "&Save", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.actionCode.setText(_translate("MainWindow", "Code", None))
        self.actionTitle.setText(_translate("MainWindow", "Title", None))
        self.actionInstructor.setText(_translate("MainWindow", "Instructor", None))
        self.actionSchedule.setText(_translate("MainWindow", "Schedule", None))
        self.actionSchedule.setToolTip(_translate("MainWindow", "Save The Image of the Schedule as a .png file", None))
        self.actionSchedule.setStatusTip(_translate("MainWindow", "Save The Image of the Schedule as a .png file", None))
        self.actionCourses.setText(_translate("MainWindow", "Courses", None))
        self.actionCourses.setToolTip(_translate("MainWindow", "Saves List of All the Courses currently in the pool.", None))
        self.actionCourses.setStatusTip(_translate("MainWindow", "Saves List of All the Courses currently in the pool.", None))
        self.action_Open.setText(_translate("MainWindow", "&Load", None))
        self.action_Open.setStatusTip(_translate("MainWindow", "Loads a list of courses from a file.", None))

